name: 'AIxplain'
description: 'Use ChatGPT to explain and suggest changes on your PR code'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
    default: ''
  github_token:
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id:
    description: 'Github PR ID'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}